name: multiGSEA
channels:
  - r
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - binutils_impl_linux-64=2.33.1
  - binutils_linux-64=2.33.1
  - bioconductor-annotationdbi=1.48.0
  - bioconductor-biobase=2.46.0
  - bioconductor-bioccheck=1.22.0
  - bioconductor-biocgenerics=0.32.0
  - bioconductor-biocparallel=1.20.0
  - bioconductor-biocstyle=2.14.0
  - bioconductor-biocviews=1.54.0
  - bioconductor-fgsea=1.12.0
  - bioconductor-graph=1.64.0
  - bioconductor-graphite=1.32.0
  - bioconductor-iranges=2.20.0
  - bioconductor-multtest=2.42.0
  - bioconductor-org.bt.eg.db=3.10.0
  - bioconductor-org.ce.eg.db=3.10.0
  - bioconductor-org.cf.eg.db=3.10.0
  - bioconductor-org.dm.eg.db=3.10.0
  - bioconductor-org.dr.eg.db=3.10.0
  - bioconductor-org.gg.eg.db=3.10.0
  - bioconductor-org.hs.eg.db=3.10.0
  - bioconductor-org.mm.eg.db=3.10.0
  - bioconductor-org.rn.eg.db=3.10.0
  - bioconductor-org.ss.eg.db=3.10.0
  - bioconductor-org.xl.eg.db=3.10.0
  - bioconductor-rbgl=1.62.1
  - bioconductor-s4vectors=0.24.0
  - bwidget=1.9.14
  - bzip2=1.0.8
  - ca-certificates=2019.11.28
  - cairo=1.16.0
  - certifi=2019.11.28
  - curl=7.68.0
  - cyrus-sasl=2.1.27
  - dbus=1.13.6
  - expat=2.2.9
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=2.001
  - font-ttf-source-code-pro=2.030
  - font-ttf-ubuntu=0.83
  - fontconfig=2.13.1
  - fonts-anaconda=1
  - freetype=2.10.0
  - gcc_impl_linux-64=7.3.0
  - gcc_linux-64=7.3.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=7.3.0
  - gfortran_linux-64=7.3.0
  - giflib=5.2.1
  - glib=2.58.3
  - graphite2=1.3.13
  - gsl=2.5
  - gst-plugins-base=1.14.5
  - gstreamer=1.14.5
  - gxx_impl_linux-64=7.3.0
  - gxx_linux-64=7.3.0
  - harfbuzz=2.4.0
  - icu=58.2
  - jpeg=9c
  - krb5=1.16.4
  - ld_impl_linux-64=2.33.1
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.68.0
  - libedit=3.1.20170329
  - libffi=3.2.1
  - libgcc-ng=9.2.0
  - libgfortran-ng=7.3.0
  - libgomp=9.2.0
  - libiconv=1.15
  - liblapack=3.8.0
  - libntlm=1.4
  - libopenblas=0.3.8
  - libpng=1.6.37
  - libssh2=1.8.2
  - libstdcxx-ng=9.2.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp=1.1.0
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.9
  - llvm-openmp=9.0.1
  - lz4-c=1.8.3
  - make=4.3
  - ncurses=6.1
  - openjdk=8.0.192
  - openssl=1.1.1f
  - pandoc=2.9.2
  - pango=1.40.14
  - pcre=8.44
  - pip=20.0.2
  - pixman=0.38.0
  - pthread-stubs=0.4
  - python=3.8.2
  - python_abi=3.8
  - qt=5.6.3
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.1.5
  - r-base=3.6.1
  - r-base64enc=0.1_3
  - r-bh=1.72.0_3
  - r-bibtex=0.4.2.2
  - r-biocmanager=1.30.4
  - r-bit=1.1_15.2
  - r-bit64=0.9_7
  - r-bitops=1.0_6
  - r-blob=1.2.1
  - r-bookdown=0.13
  - r-brew=1.0_6
  - r-broom=0.5.5
  - r-callr=3.4.2
  - r-catools=1.18.0
  - r-cellranger=1.1.0
  - r-checkmate=2.0.0
  - r-cli=2.0.2
  - r-clipr=0.7.0
  - r-clisymbols=1.2.0
  - r-codetools=0.2_16
  - r-colorspace=1.4_1
  - r-commonmark=1.7
  - r-config=0.3
  - r-covr=3.5.0
  - r-crayon=1.3.4
  - r-crosstalk=1.0.0
  - r-curl=4.3
  - r-data.table=1.12.8
  - r-dbi=1.1.0
  - r-dbplyr=1.4.2
  - r-desc=1.2.0
  - r-devtools=2.2.2
  - r-digest=0.6.25
  - r-dplyr=0.8.5
  - r-dt=0.12
  - r-ellipsis=0.3.0
  - r-evaluate=0.14
  - r-fansi=0.4.1
  - r-farver=2.0.3
  - r-fastmap=1.0.1
  - r-fastmatch=1.1_0
  - r-forcats=0.5.0
  - r-forge=0.2.0
  - r-formatr=1.7
  - r-fs=1.3.2
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-gbrd=0.4_11
  - r-generics=0.0.2
  - r-getopt=1.20.3
  - r-ggplot2=3.2.1
  - r-gh=1.1.0
  - r-git2r=0.26.1
  - r-glue=1.3.1
  - r-gridextra=2.3
  - r-gtable=0.3.0
  - r-haven=2.2.0
  - r-highr=0.8
  - r-hms=0.5.3
  - r-htmltools=0.4.0
  - r-htmlwidgets=1.5.1
  - r-httpuv=1.5.2
  - r-httr=1.4.1
  - r-ini=0.3.1
  - r-jsonlite=1.6.1
  - r-knitr=1.28
  - r-labeling=0.3
  - r-lambda.r=1.2.4
  - r-later=1.0.0
  - r-lattice=0.20_40
  - r-lazyeval=0.2.2
  - r-lifecycle=0.2.0
  - r-lubridate=1.7.4
  - r-magrittr=1.5
  - r-markdown=1.1
  - r-mass=7.3_51.5
  - r-matrix=1.2_18
  - r-memoise=1.1.0
  - r-metap=1.1
  - r-mgcv=1.8_31
  - r-mime=0.9
  - r-miniui=0.1.1.1
  - r-modelr=0.1.6
  - r-mongolite=2.1.0
  - r-munsell=0.5.0
  - r-nlme=3.1_145
  - r-odbc=1.2.2
  - r-openssl=1.4.1
  - r-optparse=1.6.2
  - r-packrat=0.5.0
  - r-pillar=1.4.3
  - r-pkgbuild=1.0.6
  - r-pkgconfig=2.0.3
  - r-pkgload=1.0.2
  - r-pki=0.1_5.1
  - r-plogr=0.2.0
  - r-plyr=1.8.6
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.4.2
  - r-profvis=0.3.6
  - r-progress=1.2.2
  - r-promises=1.1.0
  - r-ps=1.3.2
  - r-purrr=0.3.3
  - r-r2d3=0.2.3
  - r-r6=2.4.1
  - r-rappdirs=0.3.1
  - r-rcmdcheck=1.3.3
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.3
  - r-rcurl=1.98_1.1
  - r-rdpack=0.11_1
  - r-readr=1.3.1
  - r-readxl=1.3.1
  - r-rematch=1.0.1
  - r-remotes=2.1.1
  - r-reprex=0.3.0
  - r-reshape2=1.4.3
  - r-rex=1.1.2
  - r-rjava=0.9_11
  - r-rjdbc=0.2_7.1
  - r-rjsonio=1.3_1.4
  - r-rlang=0.4.5
  - r-rmarkdown=2.1
  - r-roxygen2=7.0.2
  - r-rprojroot=1.3_2
  - r-rsconnect=0.8.16
  - r-rsqlite=2.1.5
  - r-rstudioapi=0.11
  - r-runit=0.4.32
  - r-rversions=2.0.1
  - r-rvest=0.3.5
  - r-scales=1.1.0
  - r-selectr=0.4_2
  - r-sessioninfo=1.1.1
  - r-shiny=1.4.0.2
  - r-snow=0.4_3
  - r-sourcetools=0.1.7
  - r-sparklyr=1.1.0
  - r-stringdist=0.9.5.1
  - r-stringi=1.4.3
  - r-stringr=1.4.0
  - r-survival=3.1_11
  - r-sys=3.3
  - r-testthat=2.3.2
  - r-tibble=2.1.3
  - r-tidyr=1.0.2
  - r-tidyselect=1.0.0
  - r-tidyverse=1.3.0
  - r-tinytex=0.20
  - r-usethis=1.5.1
  - r-utf8=1.1.4
  - r-vctrs=0.2.3
  - r-viridislite=0.3.0
  - r-whisker=0.4
  - r-withr=2.1.2
  - r-xfun=0.12
  - r-xml=3.98_1.19
  - r-xml2=1.2.2
  - r-xopen=1.0.0
  - r-xtable=1.8_4
  - r-yaml=2.2.1
  - r-zeallot=0.1.0
  - readline=8.0
  - rstudio=1.1.456
  - sed=4.7
  - setuptools=46.0.0
  - sqlite=3.30.1
  - tk=8.6.10
  - tktable=2.10
  - unixodbc=2.3.7
  - wheel=0.34.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.9
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.4
  - zlib=1.2.11
  - zstd=1.4.4
